dist: bionic
language: python

notifications:
  email: false

python:
- "3.5"
- "3.6"
- "3.7"
- "3.8"

before_install:
- sudo apt-get install -y libopenjp2-7

install:
- if [ $TRAVIS_PYTHON_VERSION == '3.7' ]; then
    pip install -e . --upgrade ;
  else
    pip install . --upgrade ;
  fi
- pip install -r requirements-dev.txt

script:
- pylint s2cloudless/*.py
- radon cc s2cloudless/*.py -a -nb
- pytest --cov

after_success:
- if [ $TRAVIS_PYTHON_VERSION == '3.7' ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then codecov; fi
